import React, { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import { supabase } from '../../lib/supabase';
import { colors, radius, shadow, spacing } from '../../theme';
import { shortDate } from '../../lib/format';
import { type Shipment, senderName } from '../../lib/shipment';
import { getInvoice, getInvoiceStatus, getPaymentSummary, hasInvoice, INVOICE_STATUS_STYLE, invoiceSymbol, type InvoiceData } from '../../lib/invoice';

type Filter = 'all' | 'sent' | 'draft' | 'overdue';
type Row = { id: string; invoiceNumber: string; customer: string; issueDate: string; dueDate?: string; currency?: string; total: number; status: ReturnType<typeof getInvoiceStatus> };
export default function InvoicesScreen() {
  const [rows, setRows] = useState<Row[]>([]); const [filter, setFilter] = useState<Filter>('all'); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async () => { const result = await supabase.from('shipments').select('*').is('deleted_at', null).not('metadata->invoice', 'is', null).order('updated_at', { ascending: false }); const list = (((result.data as Shipment[]) || []).filter(hasInvoice).map((shipment) => { const invoice: InvoiceData = getInvoice(shipment); return { id: shipment.id, invoiceNumber: invoice.invoiceNumber || '—', customer: senderName(shipment), issueDate: invoice.issueDate || shipment.created_at, dueDate: invoice.dueDate, currency: invoice.currency, total: getPaymentSummary(invoice).total, status: getInvoiceStatus(invoice) }; })); setRows(list); setLoading(false); }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const counts = useMemo(() => ({ all: rows.length, sent: rows.filter((r) => r.status === 'sent' || r.status === 'partial').length, draft: rows.filter((r) => r.status === 'draft').length, overdue: rows.filter((r) => r.status === 'overdue').length }), [rows]);
  const filtered = useMemo(() => rows.filter((row) => filter === 'all' || (filter === 'sent' ? row.status === 'sent' || row.status === 'partial' : row.status === filter)), [rows, filter]);
  if (loading) return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View></SafeAreaView>; const refresh = async () => { setRefreshing(true); await load(); setRefreshing(false); };
  return <SafeAreaView style={styles.safe} edges={['top']}><FlatList data={filtered} keyExtractor={(row) => row.id} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.primary} />} ListHeaderComponent={<><View style={styles.header}><Text style={styles.title}>Invoices</Text><Text style={styles.subtitle}>Billing and payment status</Text></View><View style={styles.filters}>{(['all', 'sent', 'draft', 'overdue'] as Filter[]).map((key) => <Pressable key={key} onPress={() => setFilter(key)} style={[styles.filter, filter === key && styles.filterActive]}><Text style={[styles.filterText, filter === key && styles.filterTextActive]}>{key[0].toUpperCase() + key.slice(1)} {counts[key]}</Text></Pressable>)}</View></>} ListEmptyComponent={<Text style={styles.empty}>No {filter === 'all' ? '' : filter} invoices.</Text>} renderItem={({ item }) => { const tone = INVOICE_STATUS_STYLE[item.status]; return <View style={styles.row}><View style={{ flex: 1 }}><Text style={styles.number}>{item.invoiceNumber}</Text><Text style={styles.customer}>{item.customer}</Text><Text style={styles.date}>{shortDate(item.issueDate)} · {item.dueDate ? `Due ${shortDate(item.dueDate)}` : 'No due date'}</Text></View><View style={styles.right}><Text style={styles.total}>{invoiceSymbol(item.currency)}{item.total.toFixed(2)}</Text><View style={[styles.status, { backgroundColor: tone.bg }]}><Text style={[styles.statusText, { color: tone.fg }]}>{tone.label}</Text></View></View></View>; }} /></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.bg }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, content: { padding: spacing.lg, paddingBottom: 105 }, header: { marginBottom: spacing.lg }, title: { fontSize: 25, fontWeight: '800', color: colors.text }, subtitle: { fontSize: 12, color: colors.textMuted, marginTop: 2 }, filters: { flexDirection: 'row', gap: 6, marginBottom: spacing.md }, filter: { flex: 1, alignItems: 'center', backgroundColor: '#F2F4F7', borderRadius: radius.pill, paddingVertical: 8 }, filterActive: { backgroundColor: '#EEEAFF' }, filterText: { fontSize: 9.5, fontWeight: '700', color: colors.textMuted }, filterTextActive: { color: colors.purple }, row: { minHeight: 94, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderRadius: radius.md, padding: spacing.md, marginBottom: spacing.sm, ...shadow }, number: { fontSize: 13.5, fontWeight: '800', color: colors.text }, customer: { fontSize: 12, fontWeight: '700', color: colors.text, marginTop: 6 }, date: { fontSize: 10.5, color: colors.textMuted, marginTop: 3 }, right: { alignItems: 'flex-end', gap: 8 }, total: { fontSize: 13.5, fontWeight: '800', color: colors.text }, status: { borderRadius: radius.pill, paddingHorizontal: 8, paddingVertical: 4 }, statusText: { fontSize: 9.5, fontWeight: '800' }, empty: { textAlign: 'center', color: colors.textMuted, padding: 40 } });
