import React, { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import { supabase } from '../../lib/supabase';
import { moneyMap } from '../../lib/format';
import { customerName } from '../../lib/format';
import { colors, radius, shadow, spacing } from '../../theme';
import type { CustomerRecord } from './CustomersScreen';

type Filter = 'all' | 'pending' | 'paid' | 'overdue';
type Payment = { id: string; amount: number | null; currency: string | null; payment_method: string | null; payment_status: string | null; transaction_id: string | null; reconciled_at: string | null; created_at: string; shipment_id?: string | null; shipment?: { user_id?: string | null; tracking_number?: string | null; customer_reference?: string | null; metadata?: any } | null };
const paidStatuses = new Set(['completed', 'paid', 'success', 'succeeded']);
const methods: Record<string, string> = { standard: 'Card / Bank', cashOnCollection: 'Cash on Collection', payOnArrival: 'Pay on Arrival', agentQuote: 'Agent Quote' };

export default function PaymentsScreen() {
  const navigation = useNavigation<any>(); const [rows, setRows] = useState<Payment[]>([]); const [customers,setCustomers]=useState<CustomerRecord[]>([]); const [filter, setFilter] = useState<Filter>('pending'); const [query,setQuery]=useState(''); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async () => { const [result,customerResult] = await Promise.all([supabase.from('payments').select('id,amount,currency,payment_method,payment_status,transaction_id,reconciled_at,created_at,shipment_id,shipment:shipments(user_id,tracking_number,customer_reference,metadata)').order('created_at', { ascending: false }),supabase.rpc('admin_customer_records')]); setRows((result.data as any[]) || []); setCustomers((customerResult.data as CustomerRecord[])||[]); setLoading(false); }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const counts = useMemo(() => ({ all: rows.length, pending: rows.filter((r) => !paidStatuses.has((r.payment_status || '').toLowerCase()) && (r.payment_status || '').toLowerCase() !== 'overdue').length, paid: rows.filter((r) => paidStatuses.has((r.payment_status || '').toLowerCase())).length, overdue: rows.filter((r) => (r.payment_status || '').toLowerCase() === 'overdue').length }), [rows]);
  const filtered = useMemo(() => rows.filter((row) => {const match=filter === 'all' || (filter === 'paid' ? paidStatuses.has((row.payment_status || '').toLowerCase()) : filter === 'overdue' ? (row.payment_status || '').toLowerCase() === 'overdue' : !paidStatuses.has((row.payment_status || '').toLowerCase()) && (row.payment_status || '').toLowerCase() !== 'overdue');const q=query.toLowerCase();return match&&(!q||JSON.stringify(row).toLowerCase().includes(q));}), [rows, filter,query]);
  const totals=useMemo(()=>{const received:Record<string,number>={},pending:Record<string,number>={};let unreconciled=0;for(const row of rows){const target=paidStatuses.has((row.payment_status||'').toLowerCase())?received:pending;const c=row.currency||'GBP';target[c]=(target[c]||0)+Number(row.amount||0);if(!row.reconciled_at)unreconciled++;}return{received,pending,unreconciled};},[rows]);
  if (loading) return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View></SafeAreaView>;
  const refresh = async () => { setRefreshing(true); await load(); setRefreshing(false); };
  return <SafeAreaView style={styles.safe} edges={['top']}><FlatList style={{ flex: 1 }} data={filtered} keyExtractor={(row) => row.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.primary} />} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.header}><Pressable accessibilityLabel="Back" style={styles.backButton} onPress={()=>navigation.goBack()}><Ionicons name="arrow-back" size={20} color={colors.text}/></Pressable><View style={{flex:1}}><Text style={styles.title}>Payments</Text><Text style={styles.subtitle}>Verification, allocation and reconciliation</Text></View><Pressable accessibilityLabel="Proof of payment" style={styles.iconButton} onPress={() => navigation.navigate('PaymentProofs')}><Ionicons name="document-attach-outline" size={20} color={colors.primary} /></Pressable><Pressable style={styles.iconButton} onPress={() => navigation.navigate('Reconciliation')}><Ionicons name="git-compare-outline" size={20} color={colors.primary} /></Pressable></View><View style={styles.summary}><Summary label="RECEIVED" value={moneyMap(totals.received)} tone={colors.primaryDark}/><Summary label="AWAITING" value={moneyMap(totals.pending)} tone={colors.amber}/><Summary label="UNRECONCILED" value={String(totals.unreconciled)} tone={colors.blue}/></View><View style={styles.search}><Ionicons name="search" size={17} color={colors.textMuted}/><TextInput style={{flex:1}} value={query} onChangeText={setQuery} placeholder="Customer, reference or shipment"/></View><View style={styles.filters}>{(['all', 'pending', 'paid', 'overdue'] as Filter[]).map((key) => <Pressable key={key} onPress={() => setFilter(key)} style={[styles.filter, filter === key && styles.filterActive]}><Text style={[styles.filterText, filter === key && styles.filterTextActive]}>{key[0].toUpperCase() + key.slice(1)} {counts[key]}</Text></Pressable>)}</View></>} ListEmptyComponent={<Text style={styles.empty}>No {filter === 'all' ? '' : filter} payments found.</Text>} renderItem={({ item }) => {
    const status = (item.payment_status || 'pending').toLowerCase(); const paid = paidStatuses.has(status); const name = item.shipment?.metadata ? customerName(item.shipment.metadata) : 'Customer';
    const senderEmail=String(item.shipment?.metadata?.sender?.email||'').toLowerCase(); const senderPhone=String(item.shipment?.metadata?.sender?.phone||'').replace(/\D/g,'');
    const customer=customers.find(c=>Boolean(item.shipment?.user_id&&c.profileId===item.shipment.user_id)||(senderEmail&&c.email?.toLowerCase()===senderEmail)||(senderPhone&&c.phone?.replace(/\D/g,'')===senderPhone));
    const fallbackCustomer:CustomerRecord={key:`payment-${item.id}`,profileId:item.shipment?.user_id||null,fullName:name,email:senderEmail||null,phone:senderPhone||null,country:null,customerReference:item.shipment?.customer_reference||item.shipment?.tracking_number||null,pickupAddress:null,shipmentCount:item.shipment_id?1:0,quoteCount:0,lifetimeValue:Number(item.amount)||0,outstanding:paid?0:Number(item.amount)||0,currency:item.currency||'GBP',lastBooking:item.created_at,lastActivity:item.created_at,active:true};
    const openCustomer=()=>navigation.navigate('CustomerDetail',{record:customer||fallbackCustomer,shipmentId:item.shipment_id});
    return <Pressable accessibilityLabel={`Open ${name} customer account`} style={styles.paymentRow} onPress={openCustomer}><View style={{ flex: 1 }}><Text style={styles.customerName}>{name}</Text><Text style={styles.amount}>{moneyMap({ [item.currency || 'GBP']: Number(item.amount) || 0 })}</Text><Text style={styles.method}>{methods[item.payment_method || ''] || item.payment_method || 'Payment'}</Text><Text style={styles.reference}>{item.transaction_id || item.shipment?.customer_reference || item.shipment?.tracking_number || 'No reference'}</Text></View><View style={styles.rowRight}><View style={[styles.status, { backgroundColor: paid ? colors.primarySoft : status === 'overdue' ? colors.redSoft : colors.amberSoft }]}><Text style={[styles.statusText, { color: paid ? colors.primaryDark : status === 'overdue' ? colors.danger : colors.amber }]}>{paid ? 'Paid' : status === 'overdue' ? 'Overdue' : 'Payment pending'}</Text></View><Text style={styles.date}>{new Date(item.created_at).toLocaleDateString(undefined, { day: '2-digit', month: 'short' })}</Text><Ionicons name="chevron-forward" size={16} color={colors.textFaint}/></View></Pressable>;
  }} /></SafeAreaView>;
}

function Summary({label,value,tone}:{label:string;value:string;tone:string}){return <View style={styles.summaryCard}><Text style={styles.summaryLabel}>{label}</Text><Text style={[styles.summaryValue,{color:tone}]} numberOfLines={1} adjustsFontSizeToFit>{value||'—'}</Text></View>}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.bg }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, content: { padding: spacing.lg, paddingBottom: 105 }, header: { flexDirection: 'row', alignItems: 'center', gap:10, marginBottom: spacing.lg }, backButton:{width:40,height:40,borderRadius:10,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'}, title: { fontSize: 25, fontWeight: '900', color: colors.text }, subtitle: { fontSize: 12, color: colors.textMuted, marginTop: 2 }, iconButton: { width: 40, height: 40, borderRadius: 10, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, summary:{flexDirection:'row',gap:8,marginBottom:12},summaryCard:{flex:1,minWidth:0,padding:11,borderRadius:12,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},summaryLabel:{fontSize:8.5,fontWeight:'900',color:colors.textMuted},summaryValue:{fontSize:14,fontWeight:'900',marginTop:7},search:{height:44,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:10,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8,marginBottom:10}, filters: { flexDirection: 'row', gap: 6, marginBottom: spacing.md }, filter: { flex: 1, minWidth: 0, borderRadius: radius.pill, backgroundColor: '#F2F4F7', paddingVertical: 8, alignItems: 'center' }, filterActive: { backgroundColor: colors.primaryDark }, filterText: { fontSize: 9.5, fontWeight: '700', color: colors.textMuted }, filterTextActive: { color: colors.white }, paymentRow: { minHeight: 112, flexDirection: 'row', gap: spacing.sm, backgroundColor: colors.surface, borderRadius: radius.md, padding: spacing.md, marginBottom: spacing.sm, ...shadow }, customerName:{fontSize:14,fontWeight:'900',color:colors.primaryDark,marginBottom:6}, amount: { fontSize: 18, fontWeight: '900', color: colors.text }, method: { fontSize: 11.5, color: colors.textMuted, marginTop: 3 }, customer: { fontSize: 12, fontWeight: '700', color: colors.text, marginTop: 5 }, reference: { fontSize: 9.5, color: colors.textFaint, marginTop: 2 }, rowRight: { alignItems: 'flex-end', justifyContent: 'space-between' }, status: { borderRadius: radius.pill, paddingHorizontal: 8, paddingVertical: 4 }, statusText: { fontSize: 9.5, fontWeight: '800' }, date: { fontSize: 10.5, color: colors.textFaint }, empty: { textAlign: 'center', color: colors.textMuted, padding: 40 } });
