import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../lib/supabase';
import { BACKEND_PENDING_MESSAGE, isMissingBackend } from '../lib/offlineQueue';
import { colors, radius, shadow, spacing } from '../theme';
import { loadStaffBusinessConfig } from '../lib/businessConfig';

export default function DriverVehicleCheckScreen() {
  const navigation = useNavigation<any>(); const { session, profile } = useAuth(); const [vehicle, setVehicle] = useState(''); const [mileage, setMileage] = useState(''); const [fuel, setFuel] = useState(''); const [notes, setNotes] = useState(''); const [items,setItems]=useState<Array<{key:string;label:string}>>([]); const [checks, setChecks] = useState<Record<string, boolean>>({}); const [busy, setBusy] = useState(false);
  useEffect(()=>{loadStaffBusinessConfig().then((config)=>{setItems(config.operations.vehicleChecklist);setChecks(Object.fromEntries(config.operations.vehicleChecklist.map((item)=>[item.key,false])));}).catch(()=>setItems([]));},[]);
  useEffect(() => { (async () => { if (!session?.user.id) return; const result = await supabase.from('driver_runs').select('vehicle_label').eq('driver_id',session.user.id).order('run_date',{ascending:false}).limit(1).maybeSingle(); setVehicle(result.data?.vehicle_label || (profile as any)?.vehicle_label || 'Vehicle not assigned'); })(); }, [profile, session?.user.id]);
  const allGood = items.length>0&&items.every(({key}) => checks[key]);
  const submit = () => { if (!vehicle || vehicle === 'Vehicle not assigned') { Alert.alert('Vehicle not assigned','Ask dispatch to assign the vehicle before completing a check.'); return; } if (!mileage.trim()) { Alert.alert('Mileage required','Enter the current vehicle mileage.'); return; } Alert.alert(allGood ? 'Submit vehicle check?' : 'Report vehicle defects?', allGood ? 'You are confirming the vehicle and cargo are safe for the route.' : 'Dispatch will be notified. Do not start the route if the vehicle is unsafe.', [{text:'Cancel',style:'cancel'},{text:'Submit',onPress:async()=>{setBusy(true);const result=await supabase.from('driver_vehicle_checks').insert({driver_id:session?.user.id,vehicle_label:vehicle,mileage:Number(mileage),fuel_percent:fuel ? Number(fuel) : null,tyres_ok:checks.tyres_ok,lights_ok:checks.lights_ok,brakes_ok:checks.brakes_ok,mirrors_ok:checks.mirrors_ok,condition_ok:checks.condition_ok,cargo_secure:checks.cargo_secure,defect_notes:notes.trim()||null});setBusy(false);if(result.error){console.warn('Vehicle check failed',result.error.message);Alert.alert('Check not submitted',isMissingBackend(result.error)?BACKEND_PENDING_MESSAGE:'Check your connection and try again.');}else Alert.alert(allGood?'Vehicle check passed':'Defects reported',allGood?'The vehicle is cleared for today’s route.':'Dispatch has the defect report.',[{text:'Done',onPress:()=>navigation.goBack()}]);}}]); };
  return <SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable style={styles.back} onPress={()=>navigation.goBack()}><Ionicons name="arrow-back" size={22} color={colors.text}/></Pressable><Text style={styles.eyebrow}>PRE-TRIP SAFETY</Text><Text style={styles.title}>Vehicle check</Text><Text style={styles.subtitle}>Complete this while stationary, before starting the route.</Text><View style={styles.vehicle}><View style={styles.vehicleIcon}><Ionicons name="car-sport" size={26} color={colors.primary}/></View><View><Text style={styles.vehicleLabel}>ASSIGNED VEHICLE</Text><Text style={styles.vehicleName}>{vehicle || 'Loading…'}</Text></View></View><View style={styles.inputs}><View style={{flex:1}}><Text style={styles.label}>MILEAGE</Text><TextInput style={styles.input} value={mileage} onChangeText={setMileage} keyboardType="decimal-pad" placeholder="84,216"/></View><View style={{flex:1}}><Text style={styles.label}>FUEL %</Text><TextInput style={styles.input} value={fuel} onChangeText={(v)=>setFuel(v.replace(/\D/g,'').slice(0,3))} keyboardType="number-pad" placeholder="72"/></View></View><View style={styles.card}>{items.map(({key,label})=><View key={key} style={styles.row}><View style={[styles.checkIcon,checks[key]&&styles.checkIconGood]}><Ionicons name={checks[key]?'checkmark':'remove'} size={17} color={checks[key]?colors.white:colors.textFaint}/></View><Text style={styles.rowLabel}>{label}</Text><Switch value={checks[key]} onValueChange={(value)=>setChecks((current)=>({...current,[key]:value}))} trackColor={{false:'#D8DEE3',true:colors.primary}} thumbColor={colors.white}/></View>)}</View><Text style={styles.label}>DEFECT NOTES</Text><TextInput style={styles.notes} value={notes} onChangeText={setNotes} multiline placeholder="Describe any defect or concern…" placeholderTextColor={colors.textFaint}/>{!allGood?<View style={styles.warning}><Ionicons name="warning-outline" size={19} color={colors.amber}/><Text style={styles.warningText}>Unchecked safety items are treated as defects and sent to dispatch.</Text></View>:<View style={styles.good}><Ionicons name="shield-checkmark" size={19} color={colors.primary}/><Text style={styles.goodText}>All safety checks passed.</Text></View>}<Pressable style={[styles.submit,busy&&{opacity:.55}]} onPress={submit} disabled={busy||!items.length}>{busy?<ActivityIndicator color={colors.white}/>:<Text style={styles.submitText}>SUBMIT VEHICLE CHECK</Text>}</Pressable></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:spacing.lg,paddingBottom:80,gap:spacing.md},back:{width:40,height:36,justifyContent:'center'},eyebrow:{color:colors.primary,fontSize:10,fontWeight:'900',letterSpacing:1.2},title:{color:colors.text,fontSize:27,fontWeight:'900'},subtitle:{color:colors.textMuted,fontSize:12},vehicle:{backgroundColor:'#102A43',borderRadius:radius.lg,padding:spacing.lg,flexDirection:'row',alignItems:'center',gap:spacing.md,...shadow},vehicleIcon:{width:50,height:50,borderRadius:16,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},vehicleLabel:{color:'#8EDCC1',fontSize:9,fontWeight:'900',letterSpacing:.8},vehicleName:{color:colors.white,fontSize:17,fontWeight:'900',marginTop:3},inputs:{flexDirection:'row',gap:spacing.sm},label:{color:colors.textMuted,fontSize:9.5,fontWeight:'900',letterSpacing:.7},input:{marginTop:6,minHeight:46,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,backgroundColor:colors.surface,paddingHorizontal:12,color:colors.text,fontWeight:'700'},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,overflow:'hidden',...shadow},row:{minHeight:62,flexDirection:'row',alignItems:'center',gap:spacing.md,paddingHorizontal:spacing.md,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.border},checkIcon:{width:30,height:30,borderRadius:10,backgroundColor:'#EEF1F4',alignItems:'center',justifyContent:'center'},checkIconGood:{backgroundColor:colors.primary},rowLabel:{flex:1,color:colors.text,fontSize:13.5,fontWeight:'800'},notes:{minHeight:100,textAlignVertical:'top',borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surface,padding:spacing.md,color:colors.text},warning:{flexDirection:'row',gap:8,backgroundColor:colors.amberSoft,borderRadius:radius.sm,padding:spacing.md},warningText:{flex:1,color:colors.amber,fontSize:11.5,lineHeight:16,fontWeight:'600'},good:{flexDirection:'row',gap:8,backgroundColor:colors.primarySoft,borderRadius:radius.sm,padding:spacing.md},goodText:{color:colors.primaryDark,fontSize:11.5,fontWeight:'700'},submit:{minHeight:52,borderRadius:radius.md,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},submitText:{color:colors.white,fontWeight:'900',fontSize:12,letterSpacing:.5}});
