
// This file is automatically generated. Do not edit it directly.
import { Database } from './types';

export type DbTables = keyof Database['public']['Tables'];

/**
 * Helper function to safely reference table names
 * This function helps ensure that table names are valid at compile time
 */
export function tableFrom<T extends DbTables>(table: T): T {
  return table;
}

// Add specific tables that might not be in the Database type but are used in the codebase
export const AUDIT_LOGS_TABLE = 'notifications'; // We're using notifications table to log actions since audit_logs doesn't exist
